### ISSUE TITLE
POB window turns black as soon as it is off focus.

### ISSUE THREAD

**Issue by Azaktzu** [PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic#12]
Hi,
I have the problem since the last league (3.12) now. 
As soon as I tab out of POB into another window like chrome or POE, PoB turns completely black until I put the window back to the front. Everything works fine and I never have problems while using it, but when I want to put it on my second monitor or google something, pob turn black. 
I am not sure if its a problem on my side with some weird Windows 10 setting. 
I reinstalled PoB twice to make sure its not something with a bad install.

**Comment by dclamage** [comment]
@Stormwind1982 

Could you please try out this updated SimpleGraphic.dll and see if it fixes your issues?
https://github.com/dclamage/PathOfBuilding-SimpleGraphic/suites/1882687267/artifacts/36770860

Unzip the file to extract SimpleGraphic.dll
Replace SimpleGraphic.dll in your PoB installation folder with this new one
Run PoB and see if you run into any issues.
PoB will say there is an update, but do not apply it. If you apply the update, it will replace SimpleGraphic.dll with the original version.

Thanks!

**Comment by Azaktzu** [comment]
> This is mostly likely a graphical issue on your end, though can you download the SimpleGraphic.dll from this ZIP file and place it in your PoB install location? That will help determine if a new version of that DLL caused this.
> 
> https://github.com/Openarl/PathOfBuilding/blob/master/runtime-win32.zip

Sadly, this is still the only working solution for me. Even the link/file you posted on 22 Jan isn't working.

**Comment by Wires77** [comment]
This issue is almost 3 years old and is likely fixed by the SimpleGraphic v2.0 change
