### ISSUE TITLE
Config File Not Found

### ISSUE THREAD

**Issue by narcolepsea** [PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic#19]
Hello, i've tried installing POB Fork everywhere. C: drive, hard-drive, USB. Nothing will run on my pc. When I downloaded it on the USB I was able to run it on another computer that doesn't even have POE installed. Attached is the error message. Please assist.
![pob error](https://user-images.githubusercontent.com/34236830/114053372-dc7d9c00-98c9-11eb-8ce9-264d133e59f7.PNG)

**Comment by narcolepsea** [comment]
![pob error 1](https://user-images.githubusercontent.com/34236830/115069763-03be1400-9f2f-11eb-962f-c8348c28aad4.PNG)

Version 2.1 install error. Please assist if you can @Wires77

**Comment by zao** [comment]
What graphics card, driver version, and Windows version number is this?

Missing config is benign, it's optional and is created when there's info to put in it.

**Comment by narcolepsea** [comment]
Where can I find this info to send? I just updated my video driver, Nvidia GTX 1070 Ti, to 466. 11. Windows 10 Home ver 20H2
