### ISSUE TITLE
Screenshots using the console command result in a black image

### ISSUE THREAD

**Issue by Wires77** [PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic#28]
- Open the console using Ctrl + `
- Type "screenshot"
- Find the resulting image in `SimpleGraphic/Screenshots` to be completely black

**Comment by QuickStick123** [comment]
The hotkey printscreen also doesn't work and displays this error msg in console
![image](https://user-images.githubusercontent.com/31533893/180637915-140108be-b793-41c2-9585-f40b22f8f48b.png)

**Comment by Wires77** [comment]
I fixed that other issue via #29 actually.  You're just missing a folder.  I may have had the wrong DLL loaded when I posted this issue, though, since after testing that change the functionality works properly.  Gonna close this after all.
