### ISSUE TITLE
The existing 2.0 version DLL cannot be used in the existing POB

### ISSUE THREAD

**Issue by nuoxuchen** [PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic#43]
I am an individual developer. After trying to compile SimpleGraphic.DLL for x64 based on the source code, I found that it cannot be used in the existing POB and prompted "ERROR: Could not find dll named 'SimpleGraphic.dll'". Is it because no matching update has been made yet?

**Comment by zao** [comment]
The release version of Path of Building is still 32-bit. You cannot mix bitness between the EXE and DLLs in a process (without extreme hacks) - LoadLibrary will just skip past the incompatible DLLs and you get the error you see as Windows indeed cannot find any suitable DLL.

The beta version of PoB is 64-bit and significantly altered, based on my ongoing work to base the windowing and renderer on GLFW3, ANGLE, modern LuaJIT and a way more efficient renderer.

The plan is to land more changes in beta and eventually switch over the release version to the better runtime.

I'm curious, what reasons do you have to look to build your own version of SimpleGraphic?

**Comment by nuoxuchen** [comment]
> The release version of Path of Building is still 32-bit. You cannot mix bitness between the EXE and DLLs in a process (without extreme hacks) - LoadLibrary will just skip past the incompatible DLLs and you get the error you see as Windows indeed cannot find any suitable DLL.
> 
> The beta version of PoB is 64-bit and significantly altered, based on my ongoing work to base the windowing and renderer on GLFW3, ANGLE, modern LuaJIT and a way more efficient renderer.
> 
> The plan is to land more changes in beta and eventually switch over the release version to the better runtime.
> 
> I'm curious, what reasons do you have to look to build your own version of SimpleGraphic?

Thank you for your answer. I have also discovered this issue. The reason why I am trying to compile the SimpleGraphic version is because I am a player of POE China server, but currently POB does not have a Chinese compatible version. I would like to try researching and translating it myself. But my programming skills have not been used for a long time, so I want to try to understand the entire program from the basics.

**Comment by Nightblade** [comment]
Have you tried [PoeCharm](https://github.com/Chuanhsing/PoeCharm)?
